require('dotenv').config();

module.exports = {
  apps: [
    {
      name: "app",
      script: "./app.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
        GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
        GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI,
      },
      log_file: "./logs/app.log",
      out_file: "./logs/app-out.log",
      error_file: "./logs/app-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
    },
    {
      name: "email-inbox-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--inbox",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
      },
      log_file: "./logs/email-inbox-workers.log",
      out_file: "./logs/email-inbox-workers-out.log",
      error_file: "./logs/email-inbox-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
    {
      name: "email-cron-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--cron",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M", // Reduced from 500M for more aggressive restarts to prevent memory buildup
      max_restarts: 10, // Allow more restarts
      min_uptime: "30s", // Minimum uptime before considering a restart
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        NODE_OPTIONS: "--expose-gc --max-old-space-size=400",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
      },
      log_file: "./logs/email-cron-workers.log",
      out_file: "./logs/email-cron-workers-out.log",
      error_file: "./logs/email-cron-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 3000, // Reduced kill timeout for faster restarts
      restart_delay: 1000, // Reduced restart delay for faster recovery
    },
    {
      name: "email-sync-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--sync",
      instances: 1, // Single instance with internal parallelism
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
      },
      log_file: "./logs/email-sync-workers.log",
      out_file: "./logs/email-sync-workers-out.log",
      error_file: "./logs/email-sync-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
    {
      name: "email-scheduled-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--scheduled",
      instances: 1, // Single instance with internal parallelism
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
      },
      log_file: "./logs/email-scheduled-workers.log",
      out_file: "./logs/email-scheduled-workers-out.log",
      error_file: "./logs/email-scheduled-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
        {
      name: "email-send-worker",
      script: "./utils/emailQueueWorker.js",
      args: "--legacy-sync",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: {
        NODE_ENV: process.env.NODE_ENV || "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: process.env.DB_NAME,
        DB_USER: process.env.DB_USER,
        DB_PASSWORD: process.env.DB_PASSWORD,
        DB_HOST: process.env.DB_HOST,
        DB_PORT: process.env.DB_PORT,
        DB_DIALECT: process.env.DB_DIALECT,
        PORT: process.env.PORT,
        EMAIL_USER: process.env.EMAIL_USER,
        EMAIL_PASS: process.env.EMAIL_PASS,
        SENDER_EMAIL: process.env.SENDER_EMAIL,
        SENDER_PASSWORD: process.env.SENDER_PASSWORD,
        FRONTEND_URL: process.env.FRONTEND_URL,
        LOCALHOST_URL: process.env.LOCALHOST_URL,
        RABBITMQ_URL: process.env.RABBITMQ_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        SENDER_NAME: process.env.SENDER_NAME || "Mridul verma",
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        REDIS_DB: process.env.REDIS_DB,
      },
      log_file: "./logs/email-send-worker.log",
      out_file: "./logs/email-send-worker-out.log",
      error_file: "./logs/email-send-worker-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 3000,
      restart_delay: 1000,
    },
  ],
};
//hello
