module.exports = {
  apps: [
    {
      name: "app",
      script: "./app.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/app.log",
      out_file: "./logs/app-out.log",
      error_file: "./logs/app-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
    },
    {
      name: "email-inbox-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--inbox",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/email-inbox-workers.log",
      out_file: "./logs/email-inbox-workers-out.log",
      error_file: "./logs/email-inbox-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
    {
      name: "email-cron-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--cron",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M", // Reduced from 500M for more aggressive restarts to prevent memory buildup
      max_restarts: 10, // Allow more restarts
      min_uptime: "30s", // Minimum uptime before considering a restart
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--expose-gc --max-old-space-size=400",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/email-cron-workers.log",
      out_file: "./logs/email-cron-workers-out.log",
      error_file: "./logs/email-cron-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 3000, // Reduced kill timeout for faster restarts
      restart_delay: 1000, // Reduced restart delay for faster recovery
    },
    {
      name: "email-sync-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--sync",
      instances: 1, // Single instance with internal parallelism
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/email-sync-workers.log",
      out_file: "./logs/email-sync-workers-out.log",
      error_file: "./logs/email-sync-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
    {
      name: "email-scheduled-workers",
      script: "./utils/emailQueueWorker.js",
      args: "--scheduled",
      instances: 1, // Single instance with internal parallelism
      autorestart: true,
      watch: false,
      max_memory_restart: "500M", // Reduced from 1G for better memory management
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/email-scheduled-workers.log",
      out_file: "./logs/email-scheduled-workers-out.log",
      error_file: "./logs/email-scheduled-workers-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 5000,
      restart_delay: 2000,
    },
        {
      name: "email-send-worker",
      script: "./utils/emailQueueWorker.js",
      args: "--legacy-sync",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "400M",
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--expose-gc",
        DB_NAME: "crm",
        DB_USER: "root",
        DB_PASSWORD: "mridul@123",
        DB_HOST: "localhost",
        DB_PORT: "3306",
        DB_DIALECT: "mysql",
        PORT: "3056",
        EMAIL_USER: "mridulverma2533@gmail.com",
        EMAIL_PASS: "rbtb kmmo hjdk hbub",
        SENDER_EMAIL: "vermamridul641@gmail.com",
        SENDER_PASSWORD: "yktw lbwo hasg elei",
        FRONTEND_URL: "http://localhost:3056",
        LOCALHOST_URL: "http://localhost:3056",
        RABBITMQ_URL: "amqp://localhost:5672",
        JWT_SECRET:
          "1d5d2abb3d7d78ed56d186b490a82267a88b5d3ddb3c8f3db9701310527b1be4a089cf8be2957576bb3b99bebbec00a18606d430ad954479e9c6012fd6bd346f",
        SENDER_NAME: "Mridul verma",
      },
      log_file: "./logs/email-send-worker.log",
      out_file: "./logs/email-send-worker-out.log",
      error_file: "./logs/email-send-worker-error.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: false,
      kill_timeout: 3000,
      restart_delay: 1000,
    },
  ],
};
//hello
